# Generated by Django 3.2.5 on 2022-02-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\python-django\\AI_Project\\AI_Project\\media'),
        ),
    ]
