# Generated by Django 3.2.5 on 2022-03-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_member_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='static/img/L_005.png', null=True, upload_to='C:\\python-django\\AI_Project\\AI_Project\\media'),
        ),
    ]
