# Generated by Django 3.2.5 on 2022-02-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_main', '0002_fileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='imgfile',
            new_name='b_image',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='title',
            new_name='b_title',
        ),
    ]
